export const GET_SYMBOLS_REQUESTED = "GET_SYMBOLS_REQUESTED";
export const GET_SYMBOLS_SUCCEEDED = "GET_SYMBOLS_SUCCEEDED";
export const GET_SYMBOLS_FAILED = "GET_SYMBOLS_FAILED";
export const SELECT_SYMBOL = "SELECT_SYMBOL";

export const SOCKET_OPEN = "SOCKET_OPEN";
export const SOCKET_CLOSE = "SOCKET_CLOSE";
export const SOCKET_MESSAGE = "SOCKET_MESSAGE";

export const SUBSCRIBE_BOOKS_REQUESTED = "SUBSCRIBE_BOOKS_REQUESTED";
export const SUBSCRIBE_BOOKS_SUCCEEDED = "SUBSCRIBE_BOOKS_SUCCEEDED";
export const SUBSCRIBE_BOOKS_FAILED = "SUBSCRIBE_BOOKS_FAILED";
export const UNSUBSCRIBE_BOOKS_REQUESTED = "UNSUBSCRIBE_BOOKS_REQUESTED";
export const UNSUBSCRIBE_BOOKS_SUCCEEDED = "UNSUBSCRIBE_BOOKS_SUCCEEDED";
export const UNSUBSCRIBE_BOOKS_FAILED = "UNSUBSCRIBE_BOOKS_FAILED";
export const BOOKS_SNAPSHOT_RECEIVED = "BOOKS_SNAPSHOT_RECEIVED";
export const BOOKS_UPDATE_RECEIVED = "BOOKS_UPDATE_RECEIVED";

export const SUBSCRIBE_TICKER_REQUESTED = "SUBSCRIBE_TICKER_REQUESTED";
export const SUBSCRIBE_TICKER_SUCCEEDED = "SUBSCRIBE_TICKER_SUCCEEDED";
export const SUBSCRIBE_TICKER_FAILED = "SUBSCRIBE_TICKER_FAILED";
export const UNSUBSCRIBE_TICKER_REQUESTED = "UNSUBSCRIBE_TICKER_REQUESTED";
export const UNSUBSCRIBE_TICKER_SUCCEEDED = "UNSUBSCRIBE_TICKER_SUCCEEDED";
export const UNSUBSCRIBE_TICKER_FAILED = "UNSUBSCRIBE_TICKER_FAILED";
export const TICKER_UPDATE_RECEIVED = "TICKER_UPDATE_RECEIVED";

export const SUBSCRIBE_TRADES_REQUESTED = "SUBSCRIBE_TRADES_REQUESTED";
export const SUBSCRIBE_TRADES_SUCCEEDED = "SUBSCRIBE_TRADES_SUCCEEDED";
export const SUBSCRIBE_TRADES_FAILED = "SUBSCRIBE_TRADES_FAILED";
export const UNSUBSCRIBE_TRADES_REQUESTED = "UNSUBSCRIBE_TRADES_REQUESTED";
export const UNSUBSCRIBE_TRADES_SUCCEEDED = "UNSUBSCRIBE_TRADES_SUCCEEDED";
export const UNSUBSCRIBE_TRADES_FAILED = "UNSUBSCRIBE_TRADES_FAILED";
export const TRADES_SNAPSHOT_RECEIVED = "TRADES_SNAPSHOT_RECEIVED";
export const TRADES_UPDATE_RECEIVED = "TRADES_UPDATE_RECEIVED";
