export const GET_SYMBOLS_REQUESTED = "GET_SYMBOLS_REQUESTED";
export const GET_SYMBOLS_SUCCEEDED = "GET_SYMBOLS_SUCCEEDED";
export const GET_SYMBOLS_FAILED = "GET_SYMBOLS_FAILED";
export const SELECT_SYMBOL = "SELECT_SYMBOL";
