export const GET_SYMBOLS_REQUESTED = "GET_SYMBOLS_REQUESTED";
export const GET_SYMBOLS_SUCCEEDED = "GET_SYMBOLS_SUCCEEDED";
export const GET_SYMBOLS_FAILED = "GET_SYMBOLS_FAILED";
export const SELECT_SYMBOL = "SELECT_SYMBOL";

export const SOCKET_OPEN = "SOCKET_OPEN";
export const SOCKET_CLOSE = "SOCKET_CLOSE";
export const SOCKET_MESSAGE = "SOCKET_MESSAGE";

export const SUBSCRIBE_BOOKS_REQUESTED = "SUBSCRIBE_BOOKS_REQUESTED";
export const SUBSCRIBE_BOOKS_SUCCEEDED = "SUBSCRIBE_BOOKS_SUCCEEDED";
export const SUBSCRIBE_BOOKS_FAILED = "SUBSCRIBE_BOOKS_FAILED";
export const UNSUBSCRIBE_BOOKS_REQUESTED = "UNSUBSCRIBE_BOOKS_REQUESTED";
export const UNSUBSCRIBE_BOOKS_SUCCEEDED = "UNSUBSCRIBE_BOOKS_SUCCEEDED";
export const UNSUBSCRIBE_BOOKS_FAILED = "UNSUBSCRIBE_BOOKS_FAILED";
export const BOOKS_SNAPSHOT_RECEIVED = "BOOKS_SNAPSHOT_RECEIVED";
export const BOOKS_UPDATE_RECEIVED = "BOOKS_UPDATE_RECEIVED";
